name: 项目自动签到
on:
  schedule:
    # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 20表示北京时间早上4点
   - cron: '0 10 * * *'
  
jobs:
  check_in:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@main

      # 下载 git submodule
      #- uses: srt32/git-actions@v0.0.3
      #  with:
      #    args: git submodule update --init --recursive

      # 使用 node:14
      - name: 使用 Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      # npm install
      - name: npm install
        run: |
          npm install
        env:
          CI: true

      # 运行脚本
      - name: 运行脚本
        run: |
         email_account='${{ secrets.EMAIL_ACCOUNT }}' account_list='${{ secrets.ACCOUNT_LIST }}' npm start
        env:
          CI: true
