name: 手动启动
on:
  workflow_dispatch:
  
jobs:
  check_in:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master

      # 下载 git submodule
      # - uses: srt32/git-actions@v0.0.3
      # with:
      #    args: git submodule update --init --recursive

      # 使用 node:14
      - name: 使用 Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # npm install
      - name: npm install
        run: |
          npm install
        env:
          CI: true

      # 运行脚本
      - name: 运行脚本
        run: |
          email_account='${{ secrets.EMAIL_ACCOUNT }}' account_list='${{ secrets.ACCOUNT_LIST }}' npm start
        env:
          CI: true
